In [319]:
# Con skiprows estoy saltando las primeras 4 filas y el header seria la 5ta fila
# Con nrows estoy leyendo el numero de filas que indico ahi (225) desde la fila que tengo (5)
import pandas as pd
tabla1 = pd.read_csv('https://docs.google.com/spreadsheets/d/e/2PACX-1vRpSTUr2WXniw0ysnXT2blO9UELpYYoISFHjXVtoDdaFEPXoykVbpX7FXMKCLa9cFyZvpnWDspn-iQe/pub?gid=65778500&single=true&output=csv', skiprows=4, nrows=225)
tabla1

,Unnamed: 0,Unnamed: 1,Human Development Index (HDI),Unnamed: 3,Life expectancy at birth,Unnamed: 5,Expected years of schooling,Unnamed: 7,Mean years of schooling,Unnamed: 9,Gross national income (GNI) per capita,Unnamed: 11,GNI per capita rank minus HDI rank,Unnamed: 13,HDI rank
0,HDI rank,Country,Value,NaN,(years),NaN,(years),NaN,(years),NaN,(2017 PPP $),NaN,NaN,NaN,NaN
1,NaN,NaN,2021,NaN,2021,NaN,2021,a,2021,a,2021,NaN,2021,b,2020
2,NaN,VERY HIGH HUMAN DEVELOPMENT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,Switzerland,"0,962",NaN,"84,0",NaN,"16,5",NaN,"13,9",NaN,66.933,NaN,5,NaN,3
4,2,Norway,"0,961",NaN,"83,2",NaN,"18,2",c,"13,0",NaN,64.660,NaN,6,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
220,NaN,Small island developing states,"0,730",NaN,"70,3",NaN,"12,4",NaN,"9,1",NaN,16.782,NaN,—,NaN,—
221,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
222,NaN,Organisation for Economic Co-operation and Dev...,"0,899",NaN,"79,0",NaN,"16,5",NaN,"12,3",NaN,45.087,NaN,—,NaN,—
223,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
224,NaN,World,"0,732",NaN,"71,4",NaN,"12,8",NaN,"8,6",NaN,16.752,NaN,—,NaN,—

In [320]:
# Con drop voy a borrar las columnas vacias o con datos no utiles
tabla1= tabla1.drop(tabla1.columns[[3, 5, 7, 9, 11, 13]], axis=1)
tabla1

,Unnamed: 0,Unnamed: 1,Human Development Index (HDI),Life expectancy at birth,Expected years of schooling,Mean years of schooling,Gross national income (GNI) per capita,GNI per capita rank minus HDI rank,HDI rank
0,HDI rank,Country,Value,(years),(years),(years),(2017 PPP $),NaN,NaN
1,NaN,NaN,2021,2021,2021,2021,2021,2021,2020
2,NaN,VERY HIGH HUMAN DEVELOPMENT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,Switzerland,"0,962","84,0","16,5","13,9",66.933,5,3
4,2,Norway,"0,961","83,2","18,2","13,0",64.660,6,1
...,...,...,...,...,...,...,...,...,...
220,NaN,Small island developing states,"0,730","70,3","12,4","9,1",16.782,—,—
221,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
222,NaN,Organisation for Economic Co-operation and Dev...,"0,899","79,0","16,5","12,3",45.087,—,—
223,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
224,NaN,World,"0,732","71,4","12,8","8,6",16.752,—,—

In [321]:
# Limpio los espacios en cada celda
tabla1=tabla1.apply(lambda x: x.str.strip())

In [322]:
# Remplazo las comas por punto
tabla1=tabla1.replace(',','.',regex=True)
tabla1

,Unnamed: 0,Unnamed: 1,Human Development Index (HDI),Life expectancy at birth,Expected years of schooling,Mean years of schooling,Gross national income (GNI) per capita,GNI per capita rank minus HDI rank,HDI rank
0,HDI rank,Country,Value,(years),(years),(years),(2017 PPP $),NaN,NaN
1,NaN,NaN,2021,2021,2021,2021,2021,2021,2020
2,NaN,VERY HIGH HUMAN DEVELOPMENT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,Switzerland,0.962,84.0,16.5,13.9,66.933,5,3
4,2,Norway,0.961,83.2,18.2,13.0,64.660,6,1
...,...,...,...,...,...,...,...,...,...
220,NaN,Small island developing states,0.730,70.3,12.4,9.1,16.782,—,—
221,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
222,NaN,Organisation for Economic Co-operation and Dev...,0.899,79.0,16.5,12.3,45.087,—,—
223,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
224,NaN,World,0.732,71.4,12.8,8.6,16.752,—,—

In [323]:
# Remplazo .. o — por NaN
import numpy as np
tabla1.replace({'..': pd.NA, '—': pd.NA}, inplace=True)
tabla1

,Unnamed: 0,Unnamed: 1,Human Development Index (HDI),Life expectancy at birth,Expected years of schooling,Mean years of schooling,Gross national income (GNI) per capita,GNI per capita rank minus HDI rank,HDI rank
0,HDI rank,Country,Value,(years),(years),(years),(2017 PPP $),NaN,NaN
1,NaN,NaN,2021,2021,2021,2021,2021,2021,2020
2,NaN,VERY HIGH HUMAN DEVELOPMENT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,Switzerland,0.962,84.0,16.5,13.9,66.933,5,3
4,2,Norway,0.961,83.2,18.2,13.0,64.660,6,1
...,...,...,...,...,...,...,...,...,...
220,NaN,Small island developing states,0.730,70.3,12.4,9.1,16.782,<NA>,<NA>
221,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
222,NaN,Organisation for Economic Co-operation and Dev...,0.899,79.0,16.5,12.3,45.087,<NA>,<NA>
223,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
224,NaN,World,0.732,71.4,12.8,8.6,16.752,<NA>,<NA>

In [324]:
#Quise ver el nombre de esa columna porque en la siguiente no me cambiaba el nombre
tabla1.columns[2]

'Human Development Index (HDI) '

In [325]:
# Con rename estoy cambiando el nombre de las columnas
# Con drop estoy eliminando la fila 0 y 1 ya que no tiene datos utiles
tabla1 = tabla1.rename(columns={'Unnamed: 0':'HDI rank', 'Unnamed: 1':'Country', 'Human Development Index (HDI) ':'Human Development Index (HDI) (2021)', 'Life expectancy at birth': 'Life expectancy at birth (2021)', 'Expected years of schooling':'Expected years of schooling (2021)', 'Mean years of schooling':'Mean years of schooling (2021)', 'Gross national income (GNI) per capita':'Gross national income (GNI) per capita (2021)', 'GNI per capita rank minus HDI rank':'GNI per capita rank minus HDI rank (2021)', 'HDI rank':'HDI rank (2020)'})
tabla1 = tabla1.drop(tabla1.index[[0,1]])
tabla1

,HDI rank,Country,Human Development Index (HDI) (2021),Life expectancy at birth (2021),Expected years of schooling (2021),Mean years of schooling (2021),Gross national income (GNI) per capita (2021),GNI per capita rank minus HDI rank (2021),HDI rank (2020)
2,NaN,VERY HIGH HUMAN DEVELOPMENT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,Switzerland,0.962,84.0,16.5,13.9,66.933,5,3
4,2,Norway,0.961,83.2,18.2,13.0,64.660,6,1
5,3,Iceland,0.959,82.7,19.2,13.8,55.782,11,2
6,4,Hong Kong. China (SAR),0.952,85.5,17.3,12.2,62.607,6,4
...,...,...,...,...,...,...,...,...,...
220,NaN,Small island developing states,0.730,70.3,12.4,9.1,16.782,<NA>,<NA>
221,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
222,NaN,Organisation for Economic Co-operation and Dev...,0.899,79.0,16.5,12.3,45.087,<NA>,<NA>
223,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
224,NaN,World,0.732,71.4,12.8,8.6,16.752,<NA>,<NA>

In [326]:
# Convierto todas las columnas, menos Country, a float
# Veo el tipo de dato
columnas_a_convertir=tabla1.columns.drop(['Country'])
tabla1[columnas_a_convertir] = tabla1[columnas_a_convertir].apply(pd.to_numeric, errors='coerce')
tabla1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 223 entries, 2 to 224
Data columns (total 9 columns):
 #   Column                                         Non-Null Count  Dtype
---  ------                                         --------------  -----
 0   HDI rank                                       191 non-null    float64
 1   Country                                        217 non-null    object
 2   Human Development Index (HDI) (2021)           206 non-null    float64
 3   Life expectancy at birth (2021)                210 non-null    float64
 4   Expected years of schooling (2021)             208 non-null    float64
 5   Mean years of schooling (2021)                 206 non-null    float64
 6   Gross national income (GNI) per capita (2021)  208 non-null    float64
 7   GNI per capita rank minus HDI rank (2021)      191 non-null    float64
 8   HDI rank (2020)                                191 non-null    float64
dtypes: float64(8), object(1)
memory usage: 15.8+ KB

In [327]:
# Verifico que no se repitan los paises (como vemos hay algunos espacios con NaN en la columna de Coountry y por eso sale falso)
len(tabla1.Country)==len(set(tabla1.Country))

False

In [328]:
# Veo que filas tienen NaN
tabla1[tabla1.isna().any(axis=1)]

,HDI rank,Country,Human Development Index (HDI) (2021),Life expectancy at birth (2021),Expected years of schooling (2021),Mean years of schooling (2021),Gross national income (GNI) per capita (2021),GNI per capita rank minus HDI rank (2021),HDI rank (2020)
2,NaN,VERY HIGH HUMAN DEVELOPMENT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69,NaN,HIGH HUMAN DEVELOPMENT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
119,NaN,MEDIUM HUMAN DEVELOPMENT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
164,NaN,LOW HUMAN DEVELOPMENT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
197,NaN,OTHER COUNTRIES OR TERRITORIES,NaN,NaN,NaN,NaN,NaN,NaN,NaN
198,NaN,Korea (Democratic People's Rep. of),NaN,73.3,10.8,NaN,NaN,NaN,NaN
199,NaN,Monaco,NaN,85.9,NaN,NaN,NaN,NaN,NaN
200,NaN,Nauru,NaN,63.6,11.7,NaN,17.730,NaN,NaN
201,NaN,Somalia,NaN,55.3,NaN,NaN,1.018,NaN,NaN
202,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
203,NaN,Human development groups,NaN,NaN,NaN,NaN,NaN,NaN,NaN
204,NaN,Very high human development,0.896,78.5,16.5,12.3,43.752,NaN,NaN
205,NaN,High human development,0.754,74.7,14.2,8.3,15.167,NaN,NaN
206,NaN,Medium human development,0.636,67.4,11.9,6.9,6.353,NaN,NaN
207,NaN,Low human development,0.518,61.3,9.5,4.9,3.009,NaN,NaN
208,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
209,NaN,Developing countries,0.685,69.9,12.3,7.5,10.704,NaN,NaN
210,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
211,NaN,Regions,NaN,NaN,NaN,NaN,NaN,NaN,NaN
212,NaN,Arab States,0.708,70.9,12.4,8.0,13.501,NaN,NaN
213,NaN,East Asia and the Pacific,0.749,75.6,13.8,7.8,15.580,NaN,NaN
214,NaN,Europe and Central Asia,0.796,72.9,15.4,10.6,19.352,NaN,NaN
215,NaN,Latin America and the Caribbean,0.754,72.1,14.8,9.0,14.521,NaN,NaN
216,NaN,South Asia,0.632,67.9,11.6,6.7,6.481,NaN,NaN
217,NaN,Sub-Saharan Africa,0.547,60.1,10.3,6.0,3.699,NaN,NaN
218,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
219,NaN,Least developed countries,0.540,64.2,10.2,5.2,2.881,NaN,NaN
220,NaN,Small island developing states,0.730,70.3,12.4,9.1,16.782,NaN,NaN
221,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
222,NaN,Organisation for Economic Co-operation and Dev...,0.899,79.0,16.5,12.3,45.087,NaN,NaN
223,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
224,NaN,World,0.732,71.4,12.8,8.6,16.752,NaN,NaN

In [331]:
# Borro las filas en donde todas las columnas son NaN
tabla1= tabla1.dropna(how='all')
# Veo que filas tienen NaN ahora
tabla1[tabla1.isna().any(axis=1)]

,HDI rank,Country,Human Development Index (HDI) (2021),Life expectancy at birth (2021),Expected years of schooling (2021),Mean years of schooling (2021),Gross national income (GNI) per capita (2021),GNI per capita rank minus HDI rank (2021),HDI rank (2020)
2,NaN,VERY HIGH HUMAN DEVELOPMENT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69,NaN,HIGH HUMAN DEVELOPMENT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
119,NaN,MEDIUM HUMAN DEVELOPMENT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
164,NaN,LOW HUMAN DEVELOPMENT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
197,NaN,OTHER COUNTRIES OR TERRITORIES,NaN,NaN,NaN,NaN,NaN,NaN,NaN
198,NaN,Korea (Democratic People's Rep. of),NaN,73.3,10.8,NaN,NaN,NaN,NaN
199,NaN,Monaco,NaN,85.9,NaN,NaN,NaN,NaN,NaN
200,NaN,Nauru,NaN,63.6,11.7,NaN,17.730,NaN,NaN
201,NaN,Somalia,NaN,55.3,NaN,NaN,1.018,NaN,NaN
203,NaN,Human development groups,NaN,NaN,NaN,NaN,NaN,NaN,NaN
204,NaN,Very high human development,0.896,78.5,16.5,12.3,43.752,NaN,NaN
205,NaN,High human development,0.754,74.7,14.2,8.3,15.167,NaN,NaN
206,NaN,Medium human development,0.636,67.4,11.9,6.9,6.353,NaN,NaN
207,NaN,Low human development,0.518,61.3,9.5,4.9,3.009,NaN,NaN
209,NaN,Developing countries,0.685,69.9,12.3,7.5,10.704,NaN,NaN
211,NaN,Regions,NaN,NaN,NaN,NaN,NaN,NaN,NaN
212,NaN,Arab States,0.708,70.9,12.4,8.0,13.501,NaN,NaN
213,NaN,East Asia and the Pacific,0.749,75.6,13.8,7.8,15.580,NaN,NaN
214,NaN,Europe and Central Asia,0.796,72.9,15.4,10.6,19.352,NaN,NaN
215,NaN,Latin America and the Caribbean,0.754,72.1,14.8,9.0,14.521,NaN,NaN
216,NaN,South Asia,0.632,67.9,11.6,6.7,6.481,NaN,NaN
217,NaN,Sub-Saharan Africa,0.547,60.1,10.3,6.0,3.699,NaN,NaN
219,NaN,Least developed countries,0.540,64.2,10.2,5.2,2.881,NaN,NaN
220,NaN,Small island developing states,0.730,70.3,12.4,9.1,16.782,NaN,NaN
222,NaN,Organisation for Economic Co-operation and Dev...,0.899,79.0,16.5,12.3,45.087,NaN,NaN
224,NaN,World,0.732,71.4,12.8,8.6,16.752,NaN,NaN

In [332]:
# Veo que las filas (211) Regions, (203) Human development groups y (197) OTHER COUNTRIES OR TERRITORIES estan demas pero las mantengo porque son la separacion de los otros incisos. Lo necesito y no se me ocurre otra idea de agruparlo
# Pero si borrare las filas (164) LOW HUMAN DEVELOPMENT, (119) MEDIUM HUMAN DEVELOPMENT, (69) HIGH HUMAN DEVELOPMENT, (2) VERY HIGH HUMAN DEVELOPMENT
# Verifico
tabla1=tabla1.drop([2, 69, 119, 164])
tabla1[tabla1.isna().any(axis=1)]

,HDI rank,Country,Human Development Index (HDI) (2021),Life expectancy at birth (2021),Expected years of schooling (2021),Mean years of schooling (2021),Gross national income (GNI) per capita (2021),GNI per capita rank minus HDI rank (2021),HDI rank (2020)
197,NaN,OTHER COUNTRIES OR TERRITORIES,NaN,NaN,NaN,NaN,NaN,NaN,NaN
198,NaN,Korea (Democratic People's Rep. of),NaN,73.3,10.8,NaN,NaN,NaN,NaN
199,NaN,Monaco,NaN,85.9,NaN,NaN,NaN,NaN,NaN
200,NaN,Nauru,NaN,63.6,11.7,NaN,17.730,NaN,NaN
201,NaN,Somalia,NaN,55.3,NaN,NaN,1.018,NaN,NaN
203,NaN,Human development groups,NaN,NaN,NaN,NaN,NaN,NaN,NaN
204,NaN,Very high human development,0.896,78.5,16.5,12.3,43.752,NaN,NaN
205,NaN,High human development,0.754,74.7,14.2,8.3,15.167,NaN,NaN
206,NaN,Medium human development,0.636,67.4,11.9,6.9,6.353,NaN,NaN
207,NaN,Low human development,0.518,61.3,9.5,4.9,3.009,NaN,NaN
209,NaN,Developing countries,0.685,69.9,12.3,7.5,10.704,NaN,NaN
211,NaN,Regions,NaN,NaN,NaN,NaN,NaN,NaN,NaN
212,NaN,Arab States,0.708,70.9,12.4,8.0,13.501,NaN,NaN
213,NaN,East Asia and the Pacific,0.749,75.6,13.8,7.8,15.580,NaN,NaN
214,NaN,Europe and Central Asia,0.796,72.9,15.4,10.6,19.352,NaN,NaN
215,NaN,Latin America and the Caribbean,0.754,72.1,14.8,9.0,14.521,NaN,NaN
216,NaN,South Asia,0.632,67.9,11.6,6.7,6.481,NaN,NaN
217,NaN,Sub-Saharan Africa,0.547,60.1,10.3,6.0,3.699,NaN,NaN
219,NaN,Least developed countries,0.540,64.2,10.2,5.2,2.881,NaN,NaN
220,NaN,Small island developing states,0.730,70.3,12.4,9.1,16.782,NaN,NaN
222,NaN,Organisation for Economic Co-operation and Dev...,0.899,79.0,16.5,12.3,45.087,NaN,NaN
224,NaN,World,0.732,71.4,12.8,8.6,16.752,NaN,NaN

In [333]:
tabla1

,HDI rank,Country,Human Development Index (HDI) (2021),Life expectancy at birth (2021),Expected years of schooling (2021),Mean years of schooling (2021),Gross national income (GNI) per capita (2021),GNI per capita rank minus HDI rank (2021),HDI rank (2020)
3,1.0,Switzerland,0.962,84.0,16.5,13.9,66.933,5.0,3.0
4,2.0,Norway,0.961,83.2,18.2,13.0,64.660,6.0,1.0
5,3.0,Iceland,0.959,82.7,19.2,13.8,55.782,11.0,2.0
6,4.0,Hong Kong. China (SAR),0.952,85.5,17.3,12.2,62.607,6.0,4.0
7,5.0,Australia,0.951,84.5,21.1,12.7,49.238,18.0,5.0
...,...,...,...,...,...,...,...,...,...
217,NaN,Sub-Saharan Africa,0.547,60.1,10.3,6.0,3.699,NaN,NaN
219,NaN,Least developed countries,0.540,64.2,10.2,5.2,2.881,NaN,NaN
220,NaN,Small island developing states,0.730,70.3,12.4,9.1,16.782,NaN,NaN
222,NaN,Organisation for Economic Co-operation and Dev...,0.899,79.0,16.5,12.3,45.087,NaN,NaN
224,NaN,World,0.732,71.4,12.8,8.6,16.752,NaN,NaN

In [349]:
# Por otro lado, veo que la (164) LOW HUMAN DEVELOPMENT, (119) MEDIUM HUMAN DEVELOPMENT, (69) HIGH HUMAN DEVELOPMENT, (2) VERY HIGH HUMAN DEVELOPMENT, para estos casos, como se repiten en gran parte del cuadro, creare una nueva columna 'Human development groups'
valores = ['VERY HIGH HUMAN DEVELOPMENT'] * 66 + ['HIGH HUMAN DEVELOPMENT'] * 49 + ['MEDIUM HUMAN DEVELOPMENT'] * 44 + ['LOW HUMAN DEVELOPMENT'] * 32 + ['NAN'] * 22
valores_repetidos = (valores * ((len(tabla1) // len(tabla1)) + 1))[:len(tabla1)]
tabla1['Human development groups']=valores_repetidos
tabla1

,HDI rank,Country,Human Development Index (HDI) (2021),Life expectancy at birth (2021),Expected years of schooling (2021),Mean years of schooling (2021),Gross national income (GNI) per capita (2021),GNI per capita rank minus HDI rank (2021),HDI rank (2020),Human development groups
3,1.0,Switzerland,0.962,84.0,16.5,13.9,66.933,5.0,3.0,VERY HIGH HUMAN DEVELOPMENT
4,2.0,Norway,0.961,83.2,18.2,13.0,64.660,6.0,1.0,VERY HIGH HUMAN DEVELOPMENT
5,3.0,Iceland,0.959,82.7,19.2,13.8,55.782,11.0,2.0,VERY HIGH HUMAN DEVELOPMENT
6,4.0,Hong Kong. China (SAR),0.952,85.5,17.3,12.2,62.607,6.0,4.0,VERY HIGH HUMAN DEVELOPMENT
7,5.0,Australia,0.951,84.5,21.1,12.7,49.238,18.0,5.0,VERY HIGH HUMAN DEVELOPMENT
...,...,...,...,...,...,...,...,...,...,...
217,NaN,Sub-Saharan Africa,0.547,60.1,10.3,6.0,3.699,NaN,NaN,NAN
219,NaN,Least developed countries,0.540,64.2,10.2,5.2,2.881,NaN,NaN,NAN
220,NaN,Small island developing states,0.730,70.3,12.4,9.1,16.782,NaN,NaN,NAN
222,NaN,Organisation for Economic Co-operation and Dev...,0.899,79.0,16.5,12.3,45.087,NaN,NaN,NAN
224,NaN,World,0.732,71.4,12.8,8.6,16.752,NaN,NaN,NAN

In [363]:
# Queria ver si funciono xd (probe con 65-66-114-115-158-159-190-191 que eran justo los intervalos de cambio :D)
tabla1.iloc[158]

HDI rank                                                            159.0
Country                                                     Côte d'Ivoire
Human Development Index (HDI) (2021)                                 0.55
Life expectancy at birth (2021)                                      58.6
Expected years of schooling (2021)                                   10.7
Mean years of schooling (2021)                                        5.2
Gross national income (GNI) per capita (2021)                       5.217
GNI per capita rank minus HDI rank (2021)                           -22.0
HDI rank (2020)                                                     159.0
Human development groups                         MEDIUM HUMAN DEVELOPMENT
Name: 163, dtype: object

In [365]:
# Reviso los tipos de datos de la tabla
tabla1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 213 entries, 3 to 224
Data columns (total 10 columns):
 #   Column                                         Non-Null Count  Dtype
---  ------                                         --------------  -----
 0   HDI rank                                       191 non-null    float64
 1   Country                                        213 non-null    object
 2   Human Development Index (HDI) (2021)           206 non-null    float64
 3   Life expectancy at birth (2021)                210 non-null    float64
 4   Expected years of schooling (2021)             208 non-null    float64
 5   Mean years of schooling (2021)                 206 non-null    float64
 6   Gross national income (GNI) per capita (2021)  208 non-null    float64
 7   GNI per capita rank minus HDI rank (2021)      191 non-null    float64
 8   HDI rank (2020)                                191 non-null    float64
 9   Human development groups                       213 non-null    object
dtypes: float64(8), object(2)
memory usage: 18.3+ KB

In [367]:
#Resultado final de la tabla :D
tabla1

,HDI rank,Country,Human Development Index (HDI) (2021),Life expectancy at birth (2021),Expected years of schooling (2021),Mean years of schooling (2021),Gross national income (GNI) per capita (2021),GNI per capita rank minus HDI rank (2021),HDI rank (2020),Human development groups
3,1.0,Switzerland,0.962,84.0,16.5,13.9,66.933,5.0,3.0,VERY HIGH HUMAN DEVELOPMENT
4,2.0,Norway,0.961,83.2,18.2,13.0,64.660,6.0,1.0,VERY HIGH HUMAN DEVELOPMENT
5,3.0,Iceland,0.959,82.7,19.2,13.8,55.782,11.0,2.0,VERY HIGH HUMAN DEVELOPMENT
6,4.0,Hong Kong. China (SAR),0.952,85.5,17.3,12.2,62.607,6.0,4.0,VERY HIGH HUMAN DEVELOPMENT
7,5.0,Australia,0.951,84.5,21.1,12.7,49.238,18.0,5.0,VERY HIGH HUMAN DEVELOPMENT
...,...,...,...,...,...,...,...,...,...,...
217,NaN,Sub-Saharan Africa,0.547,60.1,10.3,6.0,3.699,NaN,NaN,NAN
219,NaN,Least developed countries,0.540,64.2,10.2,5.2,2.881,NaN,NaN,NAN
220,NaN,Small island developing states,0.730,70.3,12.4,9.1,16.782,NaN,NaN,NAN
222,NaN,Organisation for Economic Co-operation and Dev...,0.899,79.0,16.5,12.3,45.087,NaN,NaN,NAN
224,NaN,World,0.732,71.4,12.8,8.6,16.752,NaN,NaN,NAN